# Attempted guesses about identity of columns in the table.
# These have been inferred from column UCDs and/or names
# in the original table data.
# The algorithm which identifies these columns is not particularly reliable,
# so it is possible that these are incorrect.
id_col: 0
ra_col: -1
dec_col: -1

# This TST file generated by STIL v3.0-3

id	name	number
--	----	------
1	John	1234
2	Christian	4567
[EOD]
